apiVersion: v1
kind: Service
metadata:
  name: py-app-service1
spec:
  selector:
    app: py-app-service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
